services:
  discovery-service:
    build:
      context: ..
      dockerfile: discovery-service/Dockerfile
    image: takypok/discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      MANAGEMENT_OTLP_METRICS_EXPORT_URL: ${MANAGEMENT_OTLP_METRICS_EXPORT_URL:-http://alloy:4318/v1/metrics}
      MANAGEMENT_OTLP_TRACING_ENDPOINT: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:-http://alloy:4318/v1/traces}
    networks:
      - takypok_default
    logging:
      driver: json-file
      options:
        max-size: "500m"
        max-file: "1"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  takypok_default:
    external: true
