server:
  port: 8084

spring:
  main:
    web-application-type: reactive
  application:
    name: content-service
  config:
    import:
      - 'classpath:config/liquibase.yml'
      - 'classpath:config/r2dbc.yml'
      - 'classpath:config/oauth2.yml'
      - 'classpath:config/springdoc.yml'
      - 'classpath:management.yml'

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    io.r2dbc.postgresql.QUERY: INFO
    io.r2dbc.postgresql.PARAM: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG
