server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

spring:
  application:
    name: discovery

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      access: unrestricted
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    enabled: true
    tracing:
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}
    metrics:
      export:
        url: ${MANAGEMENT_OTLP_METRICS_EXPORT_URL:http://localhost:4318/v1/metrics}
        step: 15s
        aggregation-temporality: cumulative
        base-time-unit: seconds
  opentelemetry:
    resource-attributes:
      service.instance.id: ${HOSTNAME:${random.uuid}}
